baseURL: https://waite.wang
title: 隶笔难书

locale: zh-cn # en-us
DefaultContentLanguage: zh-cn
hasCJKLanguage: true

theme: PaperMod

author:
  name: Waite
  email: waite@waite.wang

pagination:
  disableAliases: false
  pagerSize: 8
  path: page

enableRobotsTXT: true

buildDrafts: false
buildFuture: false
buildExpired: false

enableEmoji: true
enableGitInfo: false
enableInlineShortcodes: true
ignoreLogs:
  - warning-goldmark-raw-html

minify:
  minifyOutput: true

Params:
  env: production
  title: Waite's Blog
  description: 一个记录生活和技术的地方
  author:
    name: Waite
    email: waite@waite.wang

  defaultTheme: auto
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  ShowShareButtons: false
  fancybox: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  comments: true
  ShowLastMod: true  # 显示文章更新时间
  ShowToc: true # 显示目录
  TocOpen: true # 自动展开目录

  assets:
    favicon: "/images/favicon.ico"
    disableHLJS: true
    

  homeInfoParams:
    title: "Waite's Blog"
    content: |
      隶笔难书, 但总要写点什么✍🏻.  
      欢迎来我的博客逛逛, 希望你能在这里找到些有用的内容.  
      你可以通过以下任意一种方式🤙🏻我:

  socialIcons:
    - name: github
      url: "https://github.com/Waite0603"
    - name: telegram
      url: "https://t.me/waite0603"
    - name: email
      url: "mailto:waite@waite.wang"
    - name: "rss"
      url: "/index.xml"
  editPost:
    URL: "https://github.com/Waite0603/HugoBlog/edit/main/content"
    Text: "在 GitHub 编辑"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    style: trac
menu:
  main:
    - identifier: "首页"
      name: "首页"
      url: /
      weight: 1
    - identifier: "搜索"
      name: "搜索"
      url: /search
      weight: 10
    - identifier: "分类"
      name: "分类"
      url: /categories
      weight: 20
    - identifier: "标签"
      name: "标签"
      url: /tags
      weight: 30
    - identifier: "归档"
      name: "归档"
      url: /archives
      weight: 40
    - identifier: "友链"
      name: "友链"
      url: /links
      weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON

privacy:
  vimeo:
    disabled: false
    simple: true

  x:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true